### ISSUE TITLE
Unable to upload OWASP DC Results

### ISSUE THREAD

**Issue by armanikumar** [fortify-ps/fortify-ssc-parser-owasp-dependency-check#2]
Hi,

Shown with an error "Exception: An unexpected error occurred during scan processing: com.fortify.manager.exception.FMDALException: Unable to execute batch." while uploading JSON file regenerated by OWASP DC latest version i.e. 6.0.1

Thanks,
Mani

**Comment by rsenden** [comment]
Hi,

The latest beta version (1.4-beta from Sept 25 or 28) fixes some processing
issues; can you please try that version?

If the latest beta version doesn't fix the issue, please share the
error/exception messages from ssc.log, or provide me with a copy of the
JSON file that is failing.

Thanks,
Ruud

**Comment by armanikumar** [comment]
Thanks Ruud, it is working now with the latest Beta release. One quick question - When I download FPR for analysis, I don't see the issues in FPR. is this an expected behavior?

**Comment by rsenden** [comment]
I think issues from 3rd-party products that have been imported using a
parser plugin are included in downloaded FPR files, however these issues
are not visible in any client-side products (Audit Workbench, IDE plugins,
...). If you would upload the FPR file to another SSC application version
(or to another SSC instance with the same parser plugins installed), I
expect the 3rd-party issues to show up in that application version or SSC
instance.

Op di 29 sep. 2020 om 15:27 schreef armanikumar <notifications@github.com>:

**Comment by armanikumar** [comment]
okay, got it. Thanks!

**Comment by rsenden** [comment]
I made some more changes to issue instance id calculation, as there were still some cases where duplicate id's were being generated (in particular if a scan contains multiple copies of the same file in different locations). A new release is now available: https://github.com/fortify-ps/fortify-ssc-parser-owasp-dependency-check/releases/tag/1.4
