### ISSUE TITLE
Support for version 6.x.x

### ISSUE THREAD

**Issue by T1mey** [fortify-ps/fortify-ssc-parser-owasp-dependency-check#6]
Hello,

is the plugin (v1.4.1) supporting version 6 of the OWASP dep. checker ?
We're not sure which engine version is meant?

![image](https://user-images.githubusercontent.com/10464878/111984752-126e0280-8b0c-11eb-968b-fe13fd88d5cd.png)

**Comment by rsenden** [comment]
Originally the plugin was developed for OWASP Dependency Check 5.x, hence the `[5.0, 5.2.2]` engine versions listed on the right in your screenshot. However the plugin seems to work just fine with OWASP Dependency Check 6.0.1 as well, and may also support other 6.x.x versions. 

Best is to just try it out with some sample results from the OWASP Dependency check version that you want to use. If it doesn't work, please submit an issue with more information like SSC log files and sample results that fail to import.

**Comment by T1mey** [comment]
Can confirm that it's working with 6.0.3
