### ISSUE TITLE
Reparsing

### ISSUE THREAD

**Issue by T1mey** [fortify-ps/fortify-ssc-parser-owasp-dependency-check#7]
Hello @rsenden, 

we have a quation about the parser and upload mechanismn.
If an application uses a vul. jar file and this information is found by OWASP scanner & uploaded to an SSC AppVersion.

What will happen if the jar is replaced by a newer version without a finding. So we're uploading an empty OWASP report to SCC AppVersion. 

Our assumption would be that the finding is marked as removed (or physically deleted) in SSC. Is this right ?

**Comment by rsenden** [comment]
Correct, a previously existing finding should be marked as removed if you upload a new report that no longer contains the finding. I haven't explicitly tested this though, so you may want to verify this yourself and post the results here. When testing this, it would be good to try multiple scenarios:

* Upload file with multiple findings
* Remove one finding from the file and upload again; verify that the relevant issue is no longer visible/marked as removed in SSC
* Remove all findings from the file and upload again; verify that SSC marks all relevant issues as removed

**Comment by T1mey** [comment]
Hi,

do you mean remove it out of the json manually ? which element must be removed ? Are there dependenencies to other elements?

Maybe it's better / easier to prepare a sample project and update the dependencies.
Maybe with an older version from jQuery , replcaing it with a newer one and / or delte it completly.

**Comment by rsenden** [comment]
The most fail-safe way to test this would be to prepare a sample project and update the dependencies, as this doesn't require understanding of the JSON format and will also update other attributes that may be relevant for SSC processing, like scan date.

I did some quick tests just now, and as expected SSC properly marks any issues as Removed if they existed before but are no longer present in the latest scan.
