### ISSUE TITLE
Upload of DC Results to SSC from Jenkins

### ISSUE THREAD

**Issue by ParthibanSG** [fortify-ps/fortify-ssc-parser-owasp-dependency-check#8]
Hello,

I am planning to automate the usage of Dependency Check and its results to Fortify SSC portal since it will be one stop for both code analysis and software composition analysis. Currently, I can upload results of DC manually in SSC however I would like to know how I can automate it through a plugin from Jenkins. I tried to upload DC results file through "Fortify Assessment" step and didn't work out as it will explicitly look for FPR's

Additionally, during manual upload also, we have to enable the "Third Party Results" and how can we automate all these to upload DC result into SSC?

Thanks

**Comment by rsenden** [comment]
I've had a quick look at the Fortify Jenkins plugin source code, and it looks like it requires the file to be uploaded to have an `.fpr` extension. I would recommend to submit a feature request through Micro Focus Support to add a feature for uploading 3rd-party scan results to the Fortify Jenkins plugin.

In the meantime, you could try the following steps:

1. Create a zip-file as described in the [parser plugin documentation](https://github.com/fortify-ps/fortify-ssc-parser-owasp-dependency-check#upload-results), for example named `depcheck.zip`, containing a `scan.info` file and actual OWASP Dependency Check results
2. Zip this zip-file again (so you have a zip file containing another zip file), for example named depcheck.zip.zip
3. Change the file extension from `.zip` to `.fpr`, for example `depcheck.zip.fpr`
4. Upload this zip-file using the Fortify Jenkins plugin

The process above results in an FPR file structure similar to how SSC itself would export 3rd-party scan results when downloading from the Artifacts page, so assumingly this should also work for uploading 3rd-party results. 

You could also try skipping step 2, just renaming the initial zip-file to `.fpr` (to cater for Jenkins plugin requirements). Usually SSC would accept such a zip file, but I'm not sure whether the `.fpr` extension would trigger different processing on the SSC-side.

As for the '3rd-party results' checkbox, this only worked properly up to SSC 20.1. In SSC 20.2 and later you can no longer upload raw 3rd-party results; scan results always need to be packaged in a zip file with a scan.info file that is used by SSC to determine the type of results. The '3rd-party results' checkbox is planned to be removed in 21.2.

**Comment by ParthibanSG** [comment]
@rsenden Thanks for your suggestions. I have tried out the FortifyClient step and it is working however with the jenkins plugin, even though I perform as per the parser documentation, I end up with RESTApi Exception error

I will raise a case with vendor to check on the same
